<?php
use App\Model\PrecoProdutos;
use Illuminate\Database\Seeder;

class PrecoProdutoTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $datas = [

            [
                "idproduto" => 1,
                "idprecoproduto" => 1,
                "nomeproduto" => "SAP ate  $10.000",
                "caractproduto" => "Seguro contra Roubo e Furto para carros de valor FIPE até  R$10.000, com cobertura de 100% da tab. FIPE para Perda Total quando advindo de um roubo ou furto com Assistencia Mecanica 24hs nivel nacional ",
                "descprotudo" => "",
                "dtcreate" => "2016-02-29 15:21:17-03",
                "premioliquidoproduto" => "959",
                "vlrfipeminimo" => "0",
                "vlrfipemaximo" => "10000",
                "vlrminprimparc" => "299",
                "lmiproduto" => NULL,
                "porcentfranquia" => NULL,
                "porcentfipepremio" => "100",
                "vlrminpremio" => NULL,
                "idadeaceitamin" => 0,
                "idadeaceitamax" => 20,
                "valorfranquia" => NULL,
                "indobrigrastreador" => true,
                "idcategoria" => NULL,
                "idtipoveiculo" => 1
            ],
            [
                "idproduto" => 1,
                "idprecoproduto" => 2,
                "nomeproduto" => "SAP $10.001 a $20.000",
                "caractproduto" => "Seguro contra Roubo e Furto para carros de valor FIPE entre R$10.001 e R$20.000, com cobertura de 100% da tab. FIPE para Perda Total quando advindo de um roubo ou furto com Assistencia Mecanica 24hs nacional",
                "descprotudo" => NULL,
                "dtcreate" => "2016-03-01 18:09:30.295237-03",
                "premioliquidoproduto" => "1055",
                "vlrfipeminimo" => "10001",
                "vlrfipemaximo" => "20000",
                "vlrminprimparc" => "299",
                "lmiproduto" => NULL,
                "porcentfranquia" => NULL,
                "porcentfipepremio" => "100",
                "vlrminpremio" => NULL,
                "idadeaceitamin" => 0,
                "idadeaceitamax" => 20,
                "valorfranquia" => NULL,
                "indobrigrastreador" => true,
                "idcategoria" => NULL,
                "idtipoveiculo" => 1
            ],
            [
                "idproduto" => 1,
                "idprecoproduto" => 3,
                "nomeproduto" => "SAP $20.001 a $30.000",
                "caractproduto" => "Seguro contra Roubo e Furto para carros de valor FIPE entre R$20.001 e R$30.000, com cobertura de 100% da tab. FIPE para Perda Total quando advindo de um roubo ou furto com Assistencia Mecanica 24hs nacional",
                "descprotudo" => NULL,
                "dtcreate" => "2016-03-01 18:09:30.295237-03",
                "premioliquidoproduto" => "1187",
                "vlrfipeminimo" => "20001",
                "vlrfipemaximo" => "30000",
                "vlrminprimparc" => "299",
                "lmiproduto" => NULL,
                "porcentfranquia" => NULL,
                "porcentfipepremio" => "100",
                "vlrminpremio" => NULL,
                "idadeaceitamin" => 0,
                "idadeaceitamax" => 20,
                "valorfranquia" => NULL,
                "indobrigrastreador" => true,
                "idcategoria" => NULL,
                "idtipoveiculo" => 1
            ],
            [
                "idproduto" => 1,
                "idprecoproduto" => 4,
                "nomeproduto" => "SAP $30.001 a $40.000",
                "caractproduto" => "Seguro contra Roubo e Furto para carros de valor FIPE entre R$30.001 e R$40.000, com cobertura de 100% da tab. FIPE para Perda Total quando advindo de um roubo ou furto  com Assistencia Mecanica 24hs nacional",
                "descprotudo" => NULL,
                "dtcreate" => "2016-03-01 18:28:55.591261-03",
                "premioliquidoproduto" => "1415",
                "vlrfipeminimo" => "30001",
                "vlrfipemaximo" => "40000",
                "vlrminprimparc" => "299",
                "lmiproduto" => NULL,
                "porcentfranquia" => NULL,
                "porcentfipepremio" => "100",
                "vlrminpremio" => NULL,
                "idadeaceitamin" => 0,
                "idadeaceitamax" => 20,
                "valorfranquia" => NULL,
                "indobrigrastreador" => true,
                "idcategoria" => NULL,
                "idtipoveiculo" => 1
            ],
            [
                "idproduto" => 1,
                "idprecoproduto" => 5,
                "nomeproduto" => "SAP $40.001 a $50.000",
                "caractproduto" => "Seguro contra Roubo e Furto para carros de valor FIPE entre R$40.001 e R$50.000, com cobertura de 100% da tab. FIPE para Perda Total quando advindo de um roubo ou furto com  Assistencia Mecanica 24hs nacional",
                "descprotudo" => NULL,
                "dtcreate" => "2016-03-01 18:28:55.591261-03",
                "premioliquidoproduto" => "1559",
                "vlrfipeminimo" => "40001",
                "vlrfipemaximo" => "50000",
                "vlrminprimparc" => "299",
                "lmiproduto" => NULL,
                "porcentfranquia" => NULL,
                "porcentfipepremio" => "100",
                "vlrminpremio" => NULL,
                "idadeaceitamin" => 0,
                "idadeaceitamax" => 20,
                "valorfranquia" => NULL,
                "indobrigrastreador" => true,
                "idcategoria" => NULL,
                "idtipoveiculo" => 1
            ],
            [
                "idproduto" => 1,
                "idprecoproduto" => 6,
                "nomeproduto" => "SAP $50.001 a $60.000",
                "caractproduto" => "Seguro contra Roubo e Furto para carros de valor FIPE entre R$50.001 e R$60.000, com cobertura de 100% da tab. FIPE para Perda Total quando advindo de um roubo ou furto com Assistencia Mecanica 24hs nacional",
                "descprotudo" => NULL,
                "dtcreate" => "2016-03-01 18:28:55.591261-03",
                "premioliquidoproduto" => "1799",
                "vlrfipeminimo" => "50001",
                "vlrfipemaximo" => "60000",
                "vlrminprimparc" => "299",
                "lmiproduto" => NULL,
                "porcentfranquia" => NULL,
                "porcentfipepremio" => "100",
                "vlrminpremio" => NULL,
                "idadeaceitamin" => 0,
                "idadeaceitamax" => 20,
                "valorfranquia" => NULL,
                "indobrigrastreador" => true,
                "idcategoria" => NULL,
                "idtipoveiculo" => 1
            ],
            [
                "idproduto" => 1,
                "idprecoproduto" => 7,
                "nomeproduto" => "SAP $60.001 a $70.000",
                "caractproduto" => "Seguro contra Roubo e Furto para carros de valor FIPE entre R$60.001 e R$70.000, com cobertura de 100% da tab. FIPE para Perda Total quando advindo de um roubo ou furto  com  Assistencia Mecanica 24hs  nacional",
                "descprotudo" => NULL,
                "dtcreate" => "2016-03-01 18:28:55.591261-03",
                "premioliquidoproduto" => "1847",
                "vlrfipeminimo" => "60001",
                "vlrfipemaximo" => "70000",
                "vlrminprimparc" => "299",
                "lmiproduto" => NULL,
                "porcentfranquia" => NULL,
                "porcentfipepremio" => "100",
                "vlrminpremio" => NULL,
                "idadeaceitamin" => 0,
                "idadeaceitamax" => 20,
                "valorfranquia" => NULL,
                "indobrigrastreador" => true,
                "idcategoria" => NULL,
                "idtipoveiculo" => 1
            ],
            [
                "idproduto" => 1,
                "idprecoproduto" => 8,
                "nomeproduto" => "SAP $70.001 a $80.000",
                "caractproduto" => "Seguro contra Roubo e Furto para carros de valor FIPE entre R$70.001 e R$80.000, com cobertura de 100% da tab. FIPE para Perda Total quando advindo de um roubo ou furto  com Assistencia Mecanica 24hs nacional ",
                "descprotudo" => NULL,
                "dtcreate" => "2016-03-01 18:28:55.591261-03",
                "premioliquidoproduto" => "2195",
                "vlrfipeminimo" => "70001",
                "vlrfipemaximo" => "80000",
                "vlrminprimparc" => "299",
                "lmiproduto" => NULL,
                "porcentfranquia" => NULL,
                "porcentfipepremio" => "100",
                "vlrminpremio" => NULL,
                "idadeaceitamin" => 0,
                "idadeaceitamax" => 20,
                "valorfranquia" => NULL,
                "indobrigrastreador" => true,
                "idcategoria" => NULL,
                "idtipoveiculo" => 1
            ],
            [
                "idproduto" => 1,
                "idprecoproduto" => 9,
                "nomeproduto" => "SAP $80.001 a $90.000",
                "caractproduto" => "Seguro contra Roubo e Furto para carros de valor FIPE entre R$80.001 e R$90.000, com cobertura de 100% da tab. FIPE para Perda Total quando advindo de um roubo ou furto  com Assistencia Mecanica 24hs nacional",
                "descprotudo" => NULL,
                "dtcreate" => "2016-03-01 18:28:55.591261-03",
                "premioliquidoproduto" => "2279",
                "vlrfipeminimo" => "80001",
                "vlrfipemaximo" => "90000",
                "vlrminprimparc" => "299",
                "lmiproduto" => NULL,
                "porcentfranquia" => NULL,
                "porcentfipepremio" => "100",
                "vlrminpremio" => NULL,
                "idadeaceitamin" => 0,
                "idadeaceitamax" => 20,
                "valorfranquia" => NULL,
                "indobrigrastreador" => true,
                "idcategoria" => NULL,
                "idtipoveiculo" => 1
            ],
            [
                "idproduto" => 1,
                "idprecoproduto" => 10,
                "nomeproduto" => "SAP $90.001 a $100.000",
                "caractproduto" => "Seguro contra Roubo e Furto para carros de valor FIPE entre R$90.001 e R$100.000, com cobertura de 100% da tab. FIPE para Perda Total quando advindo de um roubo ou furto  com  Assistencia Mecanica 24hs  nacional",
                "descprotudo" => NULL,
                "dtcreate" => "2016-03-01 18:28:55.591261-03",
                "premioliquidoproduto" => "2555",
                "vlrfipeminimo" => "90001",
                "vlrfipemaximo" => "100000",
                "vlrminprimparc" => "299",
                "lmiproduto" => NULL,
                "porcentfranquia" => NULL,
                "porcentfipepremio" => "100",
                "vlrminpremio" => NULL,
                "idadeaceitamin" => 0,
                "idadeaceitamax" => 20,
                "valorfranquia" => NULL,
                "indobrigrastreador" => true,
                "idcategoria" => NULL,
                "idtipoveiculo" => 1
            ],
            [
                "idproduto" => 1,
                "idprecoproduto" => 11,
                "nomeproduto" => "SAP $100.001 a $110.000",
                "caractproduto" => "Seguro contra Roubo e Furto para carros de valor FIPE entre R$100.001 e R$110.000, com cobertura de 100% da tab. FIPE para Perda Total quando advindo de um roubo ou furto  com Assistencia Mecanica 24hs  nacional",
                "descprotudo" => NULL,
                "dtcreate" => "2016-03-01 18:28:55.591261-03",
                "premioliquidoproduto" => "2555",
                "vlrfipeminimo" => "100001",
                "vlrfipemaximo" => "110000",
                "vlrminprimparc" => "299",
                "lmiproduto" => NULL,
                "porcentfranquia" => NULL,
                "porcentfipepremio" => "100",
                "vlrminpremio" => NULL,
                "idadeaceitamin" => 0,
                "idadeaceitamax" => 20,
                "valorfranquia" => NULL,
                "indobrigrastreador" => true,
                "idcategoria" => NULL,
                "idtipoveiculo" => 1
            ],
            [
                "idproduto" => 1,
                "idprecoproduto" => 12,
                "nomeproduto" => "SAP $110.001 a $120.000",
                "caractproduto" => "Seguro contra Roubo e Furto para carros de valor FIPE entre R$110.001 e R$120.000, com cobertura de 100% da tab. FIPE para Perda Total quando advindo de um roubo ou furto  com Assistencia Mecanica 24hs  nacional",
                "descprotudo" => NULL,
                "dtcreate" => "2016-03-01 18:28:55.591261-03",
                "premioliquidoproduto" => "2555",
                "vlrfipeminimo" => "110001",
                "vlrfipemaximo" => "120000",
                "vlrminprimparc" => "299",
                "lmiproduto" => NULL,
                "porcentfranquia" => NULL,
                "porcentfipepremio" => "100",
                "vlrminpremio" => NULL,
                "idadeaceitamin" => 0,
                "idadeaceitamax" => 20,
                "valorfranquia" => NULL,
                "indobrigrastreador" => true,
                "idcategoria" => NULL,
                "idtipoveiculo" => 1
            ],
            [
                "idproduto" => 1,
                "idprecoproduto" => 13,
                "nomeproduto" => "SAP $120.001 a $130.000",
                "caractproduto" => "Seguro contra Roubo e Furto para carros de valor FIPE entre R$120.001 e R$130.000, com cobertura de 100% da tab. FIPE para Perda Total quando advindo de um roubo ou furto  com Assistencia Mecanica 24hs  nacional",
                "descprotudo" => NULL,
                "dtcreate" => NULL,
                "premioliquidoproduto" => "2831",
                "vlrfipeminimo" => "120001",
                "vlrfipemaximo" => "130000",
                "vlrminprimparc" => "299",
                "lmiproduto" => NULL,
                "porcentfranquia" => NULL,
                "porcentfipepremio" => "100",
                "vlrminpremio" => NULL,
                "idadeaceitamin" => 0,
                "idadeaceitamax" => 20,
                "valorfranquia" => NULL,
                "indobrigrastreador" => true,
                "idcategoria" => NULL,
                "idtipoveiculo" => 1
            ],
            [
                "idproduto" => 1,
                "idprecoproduto" => 14,
                "nomeproduto" => "SAP $130.001 a $140.000",
                "caractproduto" => "Seguro contra Roubo e Furto para carros de valor FIPE entre R$130.001 e R$140.000, com cobertura de 100% da tab. FIPE para Perda Total quando advindo de um roubo ou furto  com Assistencia Mecanica 24hs  nacional",
                "descprotudo" => NULL,
                "dtcreate" => NULL,
                "premioliquidoproduto" => "2831",
                "vlrfipeminimo" => "130001",
                "vlrfipemaximo" => "140000",
                "vlrminprimparc" => "299",
                "lmiproduto" => NULL,
                "porcentfranquia" => NULL,
                "porcentfipepremio" => "100",
                "vlrminpremio" => NULL,
                "idadeaceitamin" => 0,
                "idadeaceitamax" => 20,
                "valorfranquia" => NULL,
                "indobrigrastreador" => true,
                "idcategoria" => NULL,
                "idtipoveiculo" => 1
            ],
            [
                "idproduto" => 1,
                "idprecoproduto" => 15,
                "nomeproduto" => "SAP $140.001 a $150.000",
                "caractproduto" => "Seguro contra Roubo e Furto para carros de valor FIPE entre R$140.001 e R$150.000, com cobertura de 100% da tab. FIPE para Perda Total quando advindo de um roubo ou furto  com Assistencia Mecanica 24hs  nacional",
                "descprotudo" => NULL,
                "dtcreate" => NULL,
                "premioliquidoproduto" => "2831",
                "vlrfipeminimo" => "140001",
                "vlrfipemaximo" => "150000",
                "vlrminprimparc" => "299",
                "lmiproduto" => NULL,
                "porcentfranquia" => NULL,
                "porcentfipepremio" => "100",
                "vlrminpremio" => NULL,
                "idadeaceitamin" => 0,
                "idadeaceitamax" => 20,
                "valorfranquia" => NULL,
                "indobrigrastreador" => true,
                "idcategoria" => NULL,
                "idtipoveiculo" => 1
            ],
            [
                "idproduto" => 1,
                "idprecoproduto" => 16,
                "nomeproduto" => "SAP-MOTO ate  $5.000",
                "caractproduto" => "Seguro contra Roubo e Furto para MOTOS de valor FIPE até R$5.000, com cobertura de 90% da tab. FIPE para Perda Total  com Assistencia Mecanica 24hs nacional ",
                "descprotudo" => NULL,
                "dtcreate" => "2016-10-19 13:20:10.60632-02",
                "premioliquidoproduto" => "1164",
                "vlrfipeminimo" => "0",
                "vlrfipemaximo" => "5000",
                "vlrminprimparc" => "299",
                "lmiproduto" => NULL,
                "porcentfranquia" => NULL,
                "porcentfipepremio" => "90",
                "vlrminpremio" => NULL,
                "idadeaceitamin" => 0,
                "idadeaceitamax" => 7,
                "valorfranquia" => NULL,
                "indobrigrastreador" => true,
                "idcategoria" => NULL,
                "idtipoveiculo" => 4
            ],
            [
                "idproduto" => 1,
                "idprecoproduto" => 17,
                "nomeproduto" => "SAP-MOTO de $5.001 a $10.000",
                "caractproduto" => "Seguro contra Roubo e Furto para MOTOS de valor FIPE de R$5.001 até R$10.000, com cobertura de 90% da tab. FIPE para Perda Total  com Assistencia Mecanica 24hs nacional ",
                "descprotudo" => NULL,
                "dtcreate" => "2016-10-19 13:20:10.60632-02",
                "premioliquidoproduto" => "1468",
                "vlrfipeminimo" => "5001",
                "vlrfipemaximo" => "10000",
                "vlrminprimparc" => "299",
                "lmiproduto" => NULL,
                "porcentfranquia" => NULL,
                "porcentfipepremio" => "90",
                "vlrminpremio" => NULL,
                "idadeaceitamin" => 0,
                "idadeaceitamax" => 7,
                "valorfranquia" => NULL,
                "indobrigrastreador" => true,
                "idcategoria" => NULL,
                "idtipoveiculo" => 4
            ],
            [
                "idproduto" => 1,
                "idprecoproduto" => 18,
                "nomeproduto" => "SAP-MOTO de $10.001 a $20.000",
                "caractproduto" => "Seguro contra Roubo e Furto para MOTOS de valor FIPE de R$10.001 até R$20.000, com cobertura de 90% da tab. FIPE para Perda Total  com Assistencia Mecanica 24hs nacional ",
                "descprotudo" => NULL,
                "dtcreate" => "2016-10-19 13:20:10.60632-02",
                "premioliquidoproduto" => "1660",
                "vlrfipeminimo" => "10001",
                "vlrfipemaximo" => "20000",
                "vlrminprimparc" => "299",
                "lmiproduto" => NULL,
                "porcentfranquia" => NULL,
                "porcentfipepremio" => "90",
                "vlrminpremio" => NULL,
                "idadeaceitamin" => 0,
                "idadeaceitamax" => 7,
                "valorfranquia" => NULL,
                "indobrigrastreador" => true,
                "idcategoria" => NULL,
                "idtipoveiculo" => 4
            ],
            [
                "idproduto" => 1,
                "idprecoproduto" => 19,
                "nomeproduto" => "SAP-MOTOde $20.001 a $30.000",
                "caractproduto" => "Seguro contra Roubo e Furto para MOTOS de valor FIPE de R$20.001 até R$30.000, com cobertura de 90% da tab. FIPE para Perda Total  com Assistencia Mecanica 24hs nacional ",
                "descprotudo" => NULL,
                "dtcreate" => "2016-10-19 13:20:10.60632-02",
                "premioliquidoproduto" => "1984",
                "vlrfipeminimo" => "20001",
                "vlrfipemaximo" => "30000",
                "vlrminprimparc" => "299",
                "lmiproduto" => NULL,
                "porcentfranquia" => NULL,
                "porcentfipepremio" => "90",
                "vlrminpremio" => NULL,
                "idadeaceitamin" => 0,
                "idadeaceitamax" => 7,
                "valorfranquia" => NULL,
                "indobrigrastreador" => true,
                "idcategoria" => NULL,
                "idtipoveiculo" => 4
            ],
            [
                "idproduto" => 1,
                "idprecoproduto" => 20,
                "nomeproduto" => "SAP-MOTO de $30.001 a $40.000",
                "caractproduto" => "Seguro contra Roubo e Furto para MOTOS de valor FIPE de R$30.001 até R$40.000, com cobertura de 90% da tab. FIPE para Perda Total  com Assistencia Mecanica 24hs nacional ",
                "descprotudo" => NULL,
                "dtcreate" => "2016-10-19 13:20:10.60632-02",
                "premioliquidoproduto" => "2424",
                "vlrfipeminimo" => "30001",
                "vlrfipemaximo" => "40000",
                "vlrminprimparc" => "299",
                "lmiproduto" => NULL,
                "porcentfranquia" => NULL,
                "porcentfipepremio" => "90",
                "vlrminpremio" => NULL,
                "idadeaceitamin" => 0,
                "idadeaceitamax" => 7,
                "valorfranquia" => NULL,
                "indobrigrastreador" => true,
                "idcategoria" => NULL,
                "idtipoveiculo" => 4
            ],
            [
                "idproduto" => 1,
                "idprecoproduto" => 21,
                "nomeproduto" => "SAP-MOTOde $40.001 a $50.000",
                "caractproduto" => "Seguro contra Roubo e Furto para MOTOS de valor FIPE de R$40.001 até R$50.000, com cobertura de 90% da tab. FIPE para Perda Total  com Assistencia Mecanica 24hs nacional ",
                "descprotudo" => NULL,
                "dtcreate" => "2016-10-19 13:20:10.60632-02",
                "premioliquidoproduto" => "2855",
                "vlrfipeminimo" => "40001",
                "vlrfipemaximo" => "50000",
                "vlrminprimparc" => "299",
                "lmiproduto" => NULL,
                "porcentfranquia" => NULL,
                "porcentfipepremio" => "90",
                "vlrminpremio" => NULL,
                "idadeaceitamin" => 0,
                "idadeaceitamax" => 7,
                "valorfranquia" => NULL,
                "indobrigrastreador" => true,
                "idcategoria" => NULL,
                "idtipoveiculo" => 4
            ],
            [
                "idproduto" => 3,
                "idprecoproduto" => 1,
                "nomeproduto" => "RCF-V Veiculo PASSEIO ",
                "caractproduto" => NULL,
                "descprotudo" => NULL,
                "dtcreate" => "2016-05-17 18:00:00-03",
                "premioliquidoproduto" => "430",
                "vlrfipeminimo" => "0",
                "vlrfipemaximo" => "200000",
                "vlrminprimparc" => NULL,
                "lmiproduto" => "50000",
                "porcentfranquia" => NULL,
                "porcentfipepremio" => NULL,
                "vlrminpremio" => NULL,
                "idadeaceitamin" => 0,
                "idadeaceitamax" => 20,
                "valorfranquia" => NULL,
                "indobrigrastreador" => false,
                "idcategoria" => 12994516,
                "idtipoveiculo" => 1
            ],
            [
                "idproduto" => 3,
                "idprecoproduto" => 2,
                "nomeproduto" => "RCF-V Pick-UP LEVE",
                "caractproduto" => NULL,
                "descprotudo" => NULL,
                "dtcreate" => "2016-05-17 18:00:00-03",
                "premioliquidoproduto" => "600",
                "vlrfipeminimo" => "0",
                "vlrfipemaximo" => "200000",
                "vlrminprimparc" => NULL,
                "lmiproduto" => "50000",
                "porcentfranquia" => NULL,
                "porcentfipepremio" => NULL,
                "vlrminpremio" => NULL,
                "idadeaceitamin" => 0,
                "idadeaceitamax" => 20,
                "valorfranquia" => NULL,
                "indobrigrastreador" => false,
                "idcategoria" => 12994520,
                "idtipoveiculo" => 1
            ],
            [
                "idproduto" => 3,
                "idprecoproduto" => 3,
                "nomeproduto" => "RCF-V  Pick-UP PESADA Passeio",
                "caractproduto" => NULL,
                "descprotudo" => NULL,
                "dtcreate" => "2016-05-17 18:00:00-03",
                "premioliquidoproduto" => "650",
                "vlrfipeminimo" => "0",
                "vlrfipemaximo" => "200000",
                "vlrminprimparc" => NULL,
                "lmiproduto" => "50000",
                "porcentfranquia" => NULL,
                "porcentfipepremio" => NULL,
                "vlrminpremio" => NULL,
                "idadeaceitamin" => 0,
                "idadeaceitamax" => 20,
                "valorfranquia" => NULL,
                "indobrigrastreador" => false,
                "idcategoria" => 12994521,
                "idtipoveiculo" => 1
            ],
            [
                "idproduto" => 3,
                "idprecoproduto" => 4,
                "nomeproduto" => "RCF-V Pick-UP PESADA CARGA",
                "caractproduto" => NULL,
                "descprotudo" => NULL,
                "dtcreate" => "2016-05-17 18:00:00-03",
                "premioliquidoproduto" => "710",
                "vlrfipeminimo" => "0",
                "vlrfipemaximo" => "200000",
                "vlrminprimparc" => NULL,
                "lmiproduto" => "50000",
                "porcentfranquia" => NULL,
                "porcentfipepremio" => NULL,
                "vlrminpremio" => NULL,
                "idadeaceitamin" => 0,
                "idadeaceitamax" => 20,
                "valorfranquia" => NULL,
                "indobrigrastreador" => false,
                "idcategoria" => 12994522,
                "idtipoveiculo" => 1
            ],
            [
                "idproduto" => 3,
                "idprecoproduto" => 5,
                "nomeproduto" => "RCF-V Veiculo PASSEIO",
                "caractproduto" => NULL,
                "descprotudo" => NULL,
                "dtcreate" => NULL,
                "premioliquidoproduto" => "523",
                "vlrfipeminimo" => "0",
                "vlrfipemaximo" => "200000",
                "vlrminprimparc" => NULL,
                "lmiproduto" => "100000",
                "porcentfranquia" => NULL,
                "porcentfipepremio" => NULL,
                "vlrminpremio" => NULL,
                "idadeaceitamin" => 0,
                "idadeaceitamax" => 20,
                "valorfranquia" => NULL,
                "indobrigrastreador" => true,
                "idcategoria" => 12994516,
                "idtipoveiculo" => 1
            ],
            [
                "idproduto" => 3,
                "idprecoproduto" => 6,
                "nomeproduto" => "RCF-V Pick-UP LEVE",
                "caractproduto" => NULL,
                "descprotudo" => NULL,
                "dtcreate" => NULL,
                "premioliquidoproduto" => "736",
                "vlrfipeminimo" => "0",
                "vlrfipemaximo" => "200000",
                "vlrminprimparc" => NULL,
                "lmiproduto" => "100000",
                "porcentfranquia" => NULL,
                "porcentfipepremio" => NULL,
                "vlrminpremio" => NULL,
                "idadeaceitamin" => 0,
                "idadeaceitamax" => 20,
                "valorfranquia" => NULL,
                "indobrigrastreador" => true,
                "idcategoria" => 12994520,
                "idtipoveiculo" => 1
            ],
            [
                "idproduto" => 3,
                "idprecoproduto" => 7,
                "nomeproduto" => "RCF-V Pick-UP PESADA Passeio",
                "caractproduto" => NULL,
                "descprotudo" => NULL,
                "dtcreate" => NULL,
                "premioliquidoproduto" => "782",
                "vlrfipeminimo" => "0",
                "vlrfipemaximo" => "200000",
                "vlrminprimparc" => NULL,
                "lmiproduto" => "100000",
                "porcentfranquia" => NULL,
                "porcentfipepremio" => NULL,
                "vlrminpremio" => NULL,
                "idadeaceitamin" => 0,
                "idadeaceitamax" => 20,
                "valorfranquia" => NULL,
                "indobrigrastreador" => true,
                "idcategoria" => 12994521,
                "idtipoveiculo" => 1
            ],
            [
                "idproduto" => 3,
                "idprecoproduto" => 8,
                "nomeproduto" => "RCF-V Pick-UP PESADA CARGA",
                "caractproduto" => NULL,
                "descprotudo" => NULL,
                "dtcreate" => NULL,
                "premioliquidoproduto" => "859",
                "vlrfipeminimo" => "0",
                "vlrfipemaximo" => "200000",
                "vlrminprimparc" => NULL,
                "lmiproduto" => "100000",
                "porcentfranquia" => NULL,
                "porcentfipepremio" => NULL,
                "vlrminpremio" => NULL,
                "idadeaceitamin" => 0,
                "idadeaceitamax" => 20,
                "valorfranquia" => NULL,
                "indobrigrastreador" => true,
                "idcategoria" => 12994522,
                "idtipoveiculo" => 1
            ],
            [
                "idproduto" => 3,
                "idprecoproduto" => 9,
                "nomeproduto" => "RCF-V Veiculo PASSEIO",
                "caractproduto" => NULL,
                "descprotudo" => NULL,
                "dtcreate" => NULL,
                "premioliquidoproduto" => "630",
                "vlrfipeminimo" => "0",
                "vlrfipemaximo" => "200000",
                "vlrminprimparc" => NULL,
                "lmiproduto" => "200000",
                "porcentfranquia" => NULL,
                "porcentfipepremio" => NULL,
                "vlrminpremio" => NULL,
                "idadeaceitamin" => 0,
                "idadeaceitamax" => 20,
                "valorfranquia" => NULL,
                "indobrigrastreador" => true,
                "idcategoria" => 12994516,
                "idtipoveiculo" => 1
            ],
            [
                "idproduto" => 3,
                "idprecoproduto" => 10,
                "nomeproduto" => "RCF-V Pick-UP LEVE",
                "caractproduto" => NULL,
                "descprotudo" => NULL,
                "dtcreate" => NULL,
                "premioliquidoproduto" => "880",
                "vlrfipeminimo" => "0",
                "vlrfipemaximo" => "200000",
                "vlrminprimparc" => NULL,
                "lmiproduto" => "200000",
                "porcentfranquia" => NULL,
                "porcentfipepremio" => NULL,
                "vlrminpremio" => NULL,
                "idadeaceitamin" => 0,
                "idadeaceitamax" => 20,
                "valorfranquia" => NULL,
                "indobrigrastreador" => true,
                "idcategoria" => 12994520,
                "idtipoveiculo" => 1
            ],
            [
                "idproduto" => 3,
                "idprecoproduto" => 11,
                "nomeproduto" => "RCF-V Pick-UP PESADA Passeio",
                "caractproduto" => NULL,
                "descprotudo" => NULL,
                "dtcreate" => NULL,
                "premioliquidoproduto" => "950",
                "vlrfipeminimo" => "0",
                "vlrfipemaximo" => "200000",
                "vlrminprimparc" => NULL,
                "lmiproduto" => "200000",
                "porcentfranquia" => NULL,
                "porcentfipepremio" => NULL,
                "vlrminpremio" => NULL,
                "idadeaceitamin" => 0,
                "idadeaceitamax" => 20,
                "valorfranquia" => NULL,
                "indobrigrastreador" => true,
                "idcategoria" => 12994521,
                "idtipoveiculo" => 1
            ],
            [
                "idproduto" => 3,
                "idprecoproduto" => 12,
                "nomeproduto" => "RCF-V Pick-UP PESADA CARGA",
                "caractproduto" => NULL,
                "descprotudo" => NULL,
                "dtcreate" => NULL,
                "premioliquidoproduto" => "1040",
                "vlrfipeminimo" => "0",
                "vlrfipemaximo" => "200000",
                "vlrminprimparc" => NULL,
                "lmiproduto" => "200000",
                "porcentfranquia" => NULL,
                "porcentfipepremio" => NULL,
                "vlrminpremio" => NULL,
                "idadeaceitamin" => 0,
                "idadeaceitamax" => 20,
                "valorfranquia" => NULL,
                "indobrigrastreador" => true,
                "idcategoria" => 12994522,
                "idtipoveiculo" => 1
            ],
            [
                "idproduto" => 4,
                "idprecoproduto" => 1,
                "nomeproduto" => "ASSISTENCIA 24hs CARRO 0 a 9 anos",
                "caractproduto" => "Assistencia Mecanica 24hs nivel nacional (USebens)",
                "descprotudo" => NULL,
                "dtcreate" => "2016-03-01 18:51:11.437042-03",
                "premioliquidoproduto" => "150",
                "vlrfipeminimo" => NULL,
                "vlrfipemaximo" => NULL,
                "vlrminprimparc" => NULL,
                "lmiproduto" => NULL,
                "porcentfranquia" => NULL,
                "porcentfipepremio" => NULL,
                "vlrminpremio" => NULL,
                "idadeaceitamin" => 0,
                "idadeaceitamax" => 9,
                "valorfranquia" => NULL,
                "indobrigrastreador" => false,
                "idcategoria" => NULL,
                "idtipoveiculo" => 1
            ],
            [
                "idproduto" => 4,
                "idprecoproduto" => 2,
                "nomeproduto" => "ASSISTENCIA 24hs CARRO 10 a 19 anos",
                "caractproduto" => "Assistencia Mecanica 24hs nivel nacional (USebens)",
                "descprotudo" => NULL,
                "dtcreate" => "2016-03-01 18:51:11.437042-03",
                "premioliquidoproduto" => "250",
                "vlrfipeminimo" => NULL,
                "vlrfipemaximo" => NULL,
                "vlrminprimparc" => NULL,
                "lmiproduto" => NULL,
                "porcentfranquia" => NULL,
                "porcentfipepremio" => NULL,
                "vlrminpremio" => NULL,
                "idadeaceitamin" => 10,
                "idadeaceitamax" => 19,
                "valorfranquia" => NULL,
                "indobrigrastreador" => false,
                "idcategoria" => NULL,
                "idtipoveiculo" => 1
            ],
            [
                "idproduto" => 4,
                "idprecoproduto" => 3,
                "nomeproduto" => "ASSISTENCIA 24hs CAMINHÃO 0 a 9 anos",
                "caractproduto" => NULL,
                "descprotudo" => NULL,
                "dtcreate" => NULL,
                "premioliquidoproduto" => "480",
                "vlrfipeminimo" => NULL,
                "vlrfipemaximo" => NULL,
                "vlrminprimparc" => NULL,
                "lmiproduto" => NULL,
                "porcentfranquia" => NULL,
                "porcentfipepremio" => NULL,
                "vlrminpremio" => NULL,
                "idadeaceitamin" => 0,
                "idadeaceitamax" => 9,
                "valorfranquia" => NULL,
                "indobrigrastreador" => false,
                "idcategoria" => NULL,
                "idtipoveiculo" => 2
            ],
            [
                "idproduto" => 4,
                "idprecoproduto" => 4,
                "nomeproduto" => "ASSISTENCIA 24hs CAMINHÃO 10 a 19 anos",
                "caractproduto" => NULL,
                "descprotudo" => NULL,
                "dtcreate" => NULL,
                "premioliquidoproduto" => "690",
                "vlrfipeminimo" => NULL,
                "vlrfipemaximo" => NULL,
                "vlrminprimparc" => NULL,
                "lmiproduto" => NULL,
                "porcentfranquia" => NULL,
                "porcentfipepremio" => NULL,
                "vlrminpremio" => NULL,
                "idadeaceitamin" => 10,
                "idadeaceitamax" => 19,
                "valorfranquia" => NULL,
                "indobrigrastreador" => false,
                "idcategoria" => NULL,
                "idtipoveiculo" => 2
            ],
            [
                "idproduto" => 4,
                "idprecoproduto" => 5,
                "nomeproduto" => "ASSISTENCIA 24hs MOTO 0 a 14 anos",
                "caractproduto" => NULL,
                "descprotudo" => NULL,
                "dtcreate" => NULL,
                "premioliquidoproduto" => "150",
                "vlrfipeminimo" => NULL,
                "vlrfipemaximo" => NULL,
                "vlrminprimparc" => NULL,
                "lmiproduto" => NULL,
                "porcentfranquia" => NULL,
                "porcentfipepremio" => NULL,
                "vlrminpremio" => NULL,
                "idadeaceitamin" => 0,
                "idadeaceitamax" => 14,
                "valorfranquia" => NULL,
                "indobrigrastreador" => false,
                "idcategoria" => NULL,
                "idtipoveiculo" => 4
            ],
            [
                "idproduto" => 5,
                "idprecoproduto" => 1,
                "nomeproduto" => "Assist. VIDROS",
                "caractproduto" => NULL,
                "descprotudo" => NULL,
                "dtcreate" => NULL,
                "premioliquidoproduto" => "190",
                "vlrfipeminimo" => "0",
                "vlrfipemaximo" => "150000",
                "vlrminprimparc" => NULL,
                "lmiproduto" => "0",
                "porcentfranquia" => NULL,
                "porcentfipepremio" => NULL,
                "vlrminpremio" => NULL,
                "idadeaceitamin" => 0,
                "idadeaceitamax" => 20,
                "valorfranquia" => NULL,
                "indobrigrastreador" => false,
                "idcategoria" => NULL,
                "idtipoveiculo" => 1
            ],
            [
                "idproduto" => 6,
                "idprecoproduto" => 1,
                "nomeproduto" => "Assist. OARA CHOQUE",
                "caractproduto" => NULL,
                "descprotudo" => NULL,
                "dtcreate" => NULL,
                "premioliquidoproduto" => "170",
                "vlrfipeminimo" => "0",
                "vlrfipemaximo" => "150000",
                "vlrminprimparc" => NULL,
                "lmiproduto" => "0",
                "porcentfranquia" => NULL,
                "porcentfipepremio" => NULL,
                "vlrminpremio" => NULL,
                "idadeaceitamin" => 0,
                "idadeaceitamax" => 20,
                "valorfranquia" => NULL,
                "indobrigrastreador" => false,
                "idcategoria" => NULL,
                "idtipoveiculo" => 1
            ],
            [
                "idproduto" => 7,
                "idprecoproduto" => 1,
                "nomeproduto" => "Assist. PINTURA",
                "caractproduto" => NULL,
                "descprotudo" => NULL,
                "dtcreate" => NULL,
                "premioliquidoproduto" => "170",
                "vlrfipeminimo" => "0",
                "vlrfipemaximo" => "150000",
                "vlrminprimparc" => NULL,
                "lmiproduto" => "0",
                "porcentfranquia" => NULL,
                "porcentfipepremio" => NULL,
                "vlrminpremio" => NULL,
                "idadeaceitamin" => 0,
                "idadeaceitamax" => 20,
                "valorfranquia" => NULL,
                "indobrigrastreador" => false,
                "idcategoria" => NULL,
                "idtipoveiculo" => 1
            ],
            [
                "idproduto" => 15,
                "idprecoproduto" => 1,
                "nomeproduto" => "Monitoramento",
                "caractproduto" => "Não é Seguro, possui 92% de taxa de sucesso de recuperação em casos de roubo e furto, comunicados dentro das 2 primeiras horas de ocorrencia. Não é atividade fim, é atividade de meio.Apoio de Pronta Resposta para recuperação de veiculo localizado. ",
                "descprotudo" => "Rastreamento veicular com apoio da Central de Monitoramento 7x24hs",
                "dtcreate" => NULL,
                "premioliquidoproduto" => "899",
                "vlrfipeminimo" => "0",
                "vlrfipemaximo" => "200000",
                "vlrminprimparc" => "299",
                "lmiproduto" => "0",
                "porcentfranquia" => NULL,
                "porcentfipepremio" => NULL,
                "vlrminpremio" => NULL,
                "idadeaceitamin" => 0,
                "idadeaceitamax" => 30,
                "valorfranquia" => NULL,
                "indobrigrastreador" => true,
                "idcategoria" => NULL,
                "idtipoveiculo" => 1
            ],
            [
                "idproduto" => 15,
                "idprecoproduto" => 2,
                "nomeproduto" => NULL,
                "caractproduto" => NULL,
                "descprotudo" => NULL,
                "dtcreate" => NULL,
                "premioliquidoproduto" => "999",
                "vlrfipeminimo" => NULL,
                "vlrfipemaximo" => NULL,
                "vlrminprimparc" => NULL,
                "lmiproduto" => NULL,
                "porcentfranquia" => NULL,
                "porcentfipepremio" => NULL,
                "vlrminpremio" => NULL,
                "idadeaceitamin" => 0,
                "idadeaceitamax" => 30,
                "valorfranquia" => NULL,
                "indobrigrastreador" => true,
                "idcategoria" => NULL,
                "idtipoveiculo" => 2
            ],
            [
                "idproduto" => 15,
                "idprecoproduto" => 3,
                "nomeproduto" => NULL,
                "caractproduto" => NULL,
                "descprotudo" => NULL,
                "dtcreate" => NULL,
                "premioliquidoproduto" => "799",
                "vlrfipeminimo" => NULL,
                "vlrfipemaximo" => NULL,
                "vlrminprimparc" => NULL,
                "lmiproduto" => NULL,
                "porcentfranquia" => NULL,
                "porcentfipepremio" => NULL,
                "vlrminpremio" => NULL,
                "idadeaceitamin" => 0,
                "idadeaceitamax" => 10,
                "valorfranquia" => NULL,
                "indobrigrastreador" => true,
                "idcategoria" => NULL,
                "idtipoveiculo" => 4
            ],
            [
                "idproduto" => 19,
                "idprecoproduto" => 1,
                "nomeproduto" => "PT $0.000 a $10.000",
                "caractproduto" => "Seguro contra PERDA TOTAL por acidente para carros de valor FIPE ate R$20.000, com cobertura de 100% da tab. FIPE (QBE) exige seguro ROUBO e FURTO tambem emitido pela QBE",
                "descprotudo" => NULL,
                "dtcreate" => NULL,
                "premioliquidoproduto" => "396",
                "vlrfipeminimo" => "0",
                "vlrfipemaximo" => "10000",
                "vlrminprimparc" => "0",
                "lmiproduto" => NULL,
                "porcentfranquia" => NULL,
                "porcentfipepremio" => "100",
                "vlrminpremio" => NULL,
                "idadeaceitamin" => 0,
                "idadeaceitamax" => 20,
                "valorfranquia" => NULL,
                "indobrigrastreador" => true,
                "idcategoria" => NULL,
                "idtipoveiculo" => 1
            ],
            [
                "idproduto" => 19,
                "idprecoproduto" => 2,
                "nomeproduto" => "PT $10.001 a $20.000",
                "caractproduto" => "Seguro contra PERDA TOTAL por acidente para carros de valor FIPE entre R$20.001 e R$30.000, com cobertura de 100% da tab. FIPE (QBE) exige seguro ROUBO e FURTO tambem emitido pela QBE",
                "descprotudo" => NULL,
                "dtcreate" => NULL,
                "premioliquidoproduto" => "440",
                "vlrfipeminimo" => "10001",
                "vlrfipemaximo" => "20000",
                "vlrminprimparc" => "0",
                "lmiproduto" => NULL,
                "porcentfranquia" => NULL,
                "porcentfipepremio" => "100",
                "vlrminpremio" => NULL,
                "idadeaceitamin" => 0,
                "idadeaceitamax" => 20,
                "valorfranquia" => NULL,
                "indobrigrastreador" => true,
                "idcategoria" => NULL,
                "idtipoveiculo" => 1
            ],
            [
                "idproduto" => 19,
                "idprecoproduto" => 3,
                "nomeproduto" => "PT $20.001 a $30.000",
                "caractproduto" => "Seguro contra PERDA TOTAL por acidente para carros de valor FIPE entre R$20.001 e R$30.000, com cobertura de 100% da tab. FIPE (QBE) exige seguro ROUBO e FURTO tambem emitido pela QBE",
                "descprotudo" => NULL,
                "dtcreate" => NULL,
                "premioliquidoproduto" => "492",
                "vlrfipeminimo" => "20001",
                "vlrfipemaximo" => "30000",
                "vlrminprimparc" => "0",
                "lmiproduto" => NULL,
                "porcentfranquia" => NULL,
                "porcentfipepremio" => "100",
                "vlrminpremio" => NULL,
                "idadeaceitamin" => 0,
                "idadeaceitamax" => 20,
                "valorfranquia" => NULL,
                "indobrigrastreador" => true,
                "idcategoria" => NULL,
                "idtipoveiculo" => 1
            ],
            [
                "idproduto" => 19,
                "idprecoproduto" => 4,
                "nomeproduto" => "PT $30.001 a $40.000",
                "caractproduto" => "Seguro contra PERDA TOTAL por acidente para carros de valor FIPE entre R$30.001 e R$40.000, com cobertura de 100% da tab. FIPE (QBE) exige seguro ROUBO e FURTO tambem emitido pela QBE",
                "descprotudo" => NULL,
                "dtcreate" => NULL,
                "premioliquidoproduto" => "552",
                "vlrfipeminimo" => "30001",
                "vlrfipemaximo" => "40000",
                "vlrminprimparc" => "0",
                "lmiproduto" => NULL,
                "porcentfranquia" => NULL,
                "porcentfipepremio" => "100",
                "vlrminpremio" => NULL,
                "idadeaceitamin" => 0,
                "idadeaceitamax" => 20,
                "valorfranquia" => NULL,
                "indobrigrastreador" => true,
                "idcategoria" => NULL,
                "idtipoveiculo" => 1
            ],
            [
                "idproduto" => 19,
                "idprecoproduto" => 5,
                "nomeproduto" => "PT $40.001 a $50.000",
                "caractproduto" => "Seguro contra PERDA TOTAL por acidente para carros de valor FIPE entre R$40.001 e R$50.000, com cobertura de 100% da tab. FIPE (QBE) exige seguro ROUBO e FURTO tambem emitido pela QBE",
                "descprotudo" => NULL,
                "dtcreate" => NULL,
                "premioliquidoproduto" => "624",
                "vlrfipeminimo" => "40001",
                "vlrfipemaximo" => "50000",
                "vlrminprimparc" => "0",
                "lmiproduto" => NULL,
                "porcentfranquia" => NULL,
                "porcentfipepremio" => "100",
                "vlrminpremio" => NULL,
                "idadeaceitamin" => 0,
                "idadeaceitamax" => 20,
                "valorfranquia" => NULL,
                "indobrigrastreador" => true,
                "idcategoria" => NULL,
                "idtipoveiculo" => 1
            ],
            [
                "idproduto" => 19,
                "idprecoproduto" => 6,
                "nomeproduto" => "PT $50.001 a $60.000",
                "caractproduto" => "Seguro contra PERDA TOTAL por acidente para carros de valor FIPE entre R$50.001 e R$60.000, com cobertura de 100% da tab. FIPE (QBE) exige seguro ROUBO e FURTO tambem emitido pela QBE",
                "descprotudo" => NULL,
                "dtcreate" => NULL,
                "premioliquidoproduto" => "852",
                "vlrfipeminimo" => "50001",
                "vlrfipemaximo" => "60000",
                "vlrminprimparc" => "0",
                "lmiproduto" => NULL,
                "porcentfranquia" => NULL,
                "porcentfipepremio" => "100",
                "vlrminpremio" => NULL,
                "idadeaceitamin" => 0,
                "idadeaceitamax" => 20,
                "valorfranquia" => NULL,
                "indobrigrastreador" => true,
                "idcategoria" => NULL,
                "idtipoveiculo" => 1
            ],
            [
                "idproduto" => 19,
                "idprecoproduto" => 7,
                "nomeproduto" => "PT $60.001 a $70.000",
                "caractproduto" => "Seguro contra PERDA TOTAL por acidente para carros de valor FIPE entre R$60.001 e R$70.000, com cobertura de 100% da tab. FIPE (QBE) exige seguro ROUBO e FURTO tambem emitido pela QBE",
                "descprotudo" => NULL,
                "dtcreate" => NULL,
                "premioliquidoproduto" => "852",
                "vlrfipeminimo" => "60001",
                "vlrfipemaximo" => "70000",
                "vlrminprimparc" => "0",
                "lmiproduto" => NULL,
                "porcentfranquia" => NULL,
                "porcentfipepremio" => "100",
                "vlrminpremio" => NULL,
                "idadeaceitamin" => 0,
                "idadeaceitamax" => 20,
                "valorfranquia" => NULL,
                "indobrigrastreador" => true,
                "idcategoria" => NULL,
                "idtipoveiculo" => 1
            ],
            [
                "idproduto" => 19,
                "idprecoproduto" => 8,
                "nomeproduto" => "PT $70.001 a $80.000",
                "caractproduto" => "Seguro contra PERDA TOTAL por acidente para carros de valor FIPE entre R$70.001 e R$80.000, com cobertura de 100% da tab. FIPE (QBE) exige seguro ROUBO e FURTO tambem emitido pela QBE",
                "descprotudo" => NULL,
                "dtcreate" => NULL,
                "premioliquidoproduto" => "1104",
                "vlrfipeminimo" => "70001",
                "vlrfipemaximo" => "80000",
                "vlrminprimparc" => "0",
                "lmiproduto" => NULL,
                "porcentfranquia" => NULL,
                "porcentfipepremio" => "100",
                "vlrminpremio" => NULL,
                "idadeaceitamin" => 0,
                "idadeaceitamax" => 20,
                "valorfranquia" => NULL,
                "indobrigrastreador" => true,
                "idcategoria" => NULL,
                "idtipoveiculo" => 1
            ],
            [
                "idproduto" => 19,
                "idprecoproduto" => 9,
                "nomeproduto" => "PT $80.001 a $90.000",
                "caractproduto" => "Seguro contra PERDA TOTAL por acidente para carros de valor FIPE entre R$80.001 e R$90.000, com cobertura de 100% da tab. FIPE (QBE) exige seguro ROUBO e FURTO tambem emitido pela QBE",
                "descprotudo" => NULL,
                "dtcreate" => NULL,
                "premioliquidoproduto" => "1104",
                "vlrfipeminimo" => "80001",
                "vlrfipemaximo" => "90000",
                "vlrminprimparc" => "0",
                "lmiproduto" => NULL,
                "porcentfranquia" => NULL,
                "porcentfipepremio" => "100",
                "vlrminpremio" => NULL,
                "idadeaceitamin" => 0,
                "idadeaceitamax" => 20,
                "valorfranquia" => NULL,
                "indobrigrastreador" => true,
                "idcategoria" => NULL,
                "idtipoveiculo" => 1
            ],
            [
                "idproduto" => 19,
                "idprecoproduto" => 10,
                "nomeproduto" => "PT $90.001 a $100.000",
                "caractproduto" => "Seguro contra PERDA TOTAL por acidente para carros de valor FIPE entre R$90.001 e R$100.000, com cobertura de 100% da tab. FIPE (QBE) exige seguro ROUBO e FURTO tambem emitido pela QBE",
                "descprotudo" => NULL,
                "dtcreate" => NULL,
                "premioliquidoproduto" => "1440",
                "vlrfipeminimo" => "90001",
                "vlrfipemaximo" => "100000",
                "vlrminprimparc" => "0",
                "lmiproduto" => NULL,
                "porcentfranquia" => NULL,
                "porcentfipepremio" => "100",
                "vlrminpremio" => NULL,
                "idadeaceitamin" => 0,
                "idadeaceitamax" => 20,
                "valorfranquia" => NULL,
                "indobrigrastreador" => true,
                "idcategoria" => NULL,
                "idtipoveiculo" => 1
            ],
            [
                "idproduto" => 19,
                "idprecoproduto" => 11,
                "nomeproduto" => "PT $100.001 a $110.000",
                "caractproduto" => "Seguro contra PERDA TOTAL por acidente para carros de valor FIPE entre R$100.001 e R$110.000, com cobertura de 100% da tab. FIPE (QBE) exige seguro ROUBO e FURTO tambem emitido pela QBE",
                "descprotudo" => NULL,
                "dtcreate" => NULL,
                "premioliquidoproduto" => "1440",
                "vlrfipeminimo" => "100001",
                "vlrfipemaximo" => "110000",
                "vlrminprimparc" => "0",
                "lmiproduto" => NULL,
                "porcentfranquia" => NULL,
                "porcentfipepremio" => "100",
                "vlrminpremio" => NULL,
                "idadeaceitamin" => 0,
                "idadeaceitamax" => 20,
                "valorfranquia" => NULL,
                "indobrigrastreador" => true,
                "idcategoria" => NULL,
                "idtipoveiculo" => 1
            ],
            [
                "idproduto" => 19,
                "idprecoproduto" => 12,
                "nomeproduto" => "PT $110.001 a $120.000",
                "caractproduto" => "Seguro contra PERDA TOTAL por acidente para carros de valor FIPE entre R$110.001 e R$120.000, com cobertura de 100% da tab. FIPE (QBE) exige seguro ROUBO e FURTO tambem emitido pela QBE",
                "descprotudo" => NULL,
                "dtcreate" => NULL,
                "premioliquidoproduto" => "1440",
                "vlrfipeminimo" => "110001",
                "vlrfipemaximo" => "120000",
                "vlrminprimparc" => "0",
                "lmiproduto" => NULL,
                "porcentfranquia" => NULL,
                "porcentfipepremio" => "100",
                "vlrminpremio" => NULL,
                "idadeaceitamin" => 0,
                "idadeaceitamax" => 20,
                "valorfranquia" => NULL,
                "indobrigrastreador" => true,
                "idcategoria" => NULL,
                "idtipoveiculo" => 1
            ],
            [
                "idproduto" => 19,
                "idprecoproduto" => 13,
                "nomeproduto" => "PT $120.001 a $130.000",
                "caractproduto" => "Seguro contra PERDA TOTAL por acidente para carros de valor FIPE entre R$120.001 e R$130.000, com cobertura de 100% da tab. FIPE (QBE) exige seguro ROUBO e FURTO tambem emitido pela QBE",
                "descprotudo" => NULL,
                "dtcreate" => NULL,
                "premioliquidoproduto" => "1692",
                "vlrfipeminimo" => "120001",
                "vlrfipemaximo" => "130000",
                "vlrminprimparc" => "0",
                "lmiproduto" => NULL,
                "porcentfranquia" => NULL,
                "porcentfipepremio" => "100",
                "vlrminpremio" => NULL,
                "idadeaceitamin" => 0,
                "idadeaceitamax" => 20,
                "valorfranquia" => NULL,
                "indobrigrastreador" => true,
                "idcategoria" => NULL,
                "idtipoveiculo" => 1
            ],
            [
                "idproduto" => 19,
                "idprecoproduto" => 14,
                "nomeproduto" => "PT $130.001 a $140.000",
                "caractproduto" => "Seguro contra PERDA TOTAL por acidente para carros de valor FIPE entre R$130.001 e R$140.000, com cobertura de 100% da tab. FIPE (QBE) exige seguro ROUBO e FURTO tambem emitido pela QBE",
                "descprotudo" => NULL,
                "dtcreate" => NULL,
                "premioliquidoproduto" => "1692",
                "vlrfipeminimo" => "130001",
                "vlrfipemaximo" => "140000",
                "vlrminprimparc" => "0",
                "lmiproduto" => NULL,
                "porcentfranquia" => NULL,
                "porcentfipepremio" => "100",
                "vlrminpremio" => NULL,
                "idadeaceitamin" => 0,
                "idadeaceitamax" => 20,
                "valorfranquia" => NULL,
                "indobrigrastreador" => true,
                "idcategoria" => NULL,
                "idtipoveiculo" => 1
            ],
            [
                "idproduto" => 19,
                "idprecoproduto" => 15,
                "nomeproduto" => "PT $140.001 a $150.000",
                "caractproduto" => "Seguro contra PERDA TOTAL por acidente para carros de valor FIPE entre R$140.001 e R$150.000, com cobertura de 100% da tab. FIPE (QBE) exige seguro ROUBO e FURTO tambem emitido pela QBE",
                "descprotudo" => NULL,
                "dtcreate" => NULL,
                "premioliquidoproduto" => "1692",
                "vlrfipeminimo" => "140001",
                "vlrfipemaximo" => "150000",
                "vlrminprimparc" => "0",
                "lmiproduto" => NULL,
                "porcentfranquia" => NULL,
                "porcentfipepremio" => "100",
                "vlrminpremio" => NULL,
                "idadeaceitamin" => 0,
                "idadeaceitamax" => 20,
                "valorfranquia" => NULL,
                "indobrigrastreador" => true,
                "idcategoria" => NULL,
                "idtipoveiculo" => 1
            ],
            [
                "idproduto" => 22,
                "idprecoproduto" => 1,
                "nomeproduto" => "Acesso Web ",
                "caractproduto" => "Acesso WEB",
                "descprotudo" => "Acesso WEB",
                "dtcreate" => NULL,
                "premioliquidoproduto" => "120",
                "vlrfipeminimo" => "0",
                "vlrfipemaximo" => "60000",
                "vlrminprimparc" => NULL,
                "lmiproduto" => "0",
                "porcentfranquia" => NULL,
                "porcentfipepremio" => NULL,
                "vlrminpremio" => NULL,
                "idadeaceitamin" => 0,
                "idadeaceitamax" => 30,
                "valorfranquia" => NULL,
                "indobrigrastreador" => true,
                "idcategoria" => NULL,
                "idtipoveiculo" => 1
            ],
            [
                "idproduto" => 22,
                "idprecoproduto" => 2,
                "nomeproduto" => "Acesso Web ",
                "caractproduto" => "Acesso Web ",
                "descprotudo" => "Acesso Web ",
                "dtcreate" => NULL,
                "premioliquidoproduto" => "160",
                "vlrfipeminimo" => "60001",
                "vlrfipemaximo" => "1000000",
                "vlrminprimparc" => NULL,
                "lmiproduto" => "0",
                "porcentfranquia" => NULL,
                "porcentfipepremio" => NULL,
                "vlrminpremio" => NULL,
                "idadeaceitamin" => 0,
                "idadeaceitamax" => 30,
                "valorfranquia" => NULL,
                "indobrigrastreador" => true,
                "idcategoria" => NULL,
                "idtipoveiculo" => 1
            ],
        ];
        
        foreach ($datas as $data){
            
            $preco =  PrecoProdutos::firstOrCreate(['idproduto'=>$data['idproduto'],'idprecoproduto'=>$data['idprecoproduto']]);
            $preco->update($data);
            
            PrecoProdutos::where('idproduto',10)->delete();
        }
    }
}
